#!/bin/bash -ex
#
# run https://github.com/avast/apkparser on the whole collection

i=0
for f in /data/malware-apks/androzoo/top10ish-per-tracker-sdk/*.apk \
             /data/malware-apks/known-good/f-droid.org/*/*.apk \
             /data/malware-apks/ikarus/*/*_[0-9]* \
             /data/malware-apks/random-google-play/*.apk \
             /data/malware-apks/covid-19-set/*/*.apk \
             /data/malware-apks/github.com/*/*/*/*/*/*.apk; do
    outpath=${f#/data/malware-apks/}
    outpath=${outpath#/data/ttt-apks/}
    output=/data/ttt-apks/extracted-features/apkparser-axml2xml/${outpath}.AndroidManifest.xml
    test -e $output && continue
    test -d $(dirname $output) || mkdir -p $(dirname $output)
    ~/go/bin/axml2xml -a "$f" > "$output" &
    i=$((i+1))
    if [ $i -gt `nproc` ]; then
    wait
    i=0
    fi
done
