#! /bin/bash
# loop over csv files and extract only the host (csv files have the following schema):
# scheme,credential,subdomain,domain,domain_without_tld,host,tld,port,resource_path,query_string,fragment,url_type

# TODO: currently only extracts hosts for ikarus dataset => add and run on other datasets once pipeline is complete

base_path=/data/ttt-apks/extracted-features/unzip-faup/ikarus
in_path_adware=$base_path/adware 
in_path_clean=$base_path/clean
out_path_adware=$(echo $in_path_adware | sed 's/unzip-faup/faup-hosts/')
out_path_clean=$(echo $in_path_clean | sed 's/unzip-faup/faup-hosts/')

echo "creating directory $out_path_adware"
echo "creating directory $out_path_clean"

mkdir -p $out_path_adware $out_path_clean

for f in $in_path_adware/*.csv $in_path_clean/*.csv; do
	target=$(echo $f | sed 's/unzip-faup/faup-hosts/')
	cut -d ',' -f 6 $f | sed 's/^[^a-zA-Z0-9]*//g' | sort | uniq > $target
done
