#!/bin/bash -x

export LC_ALL=C.UTF-8

i=0
for f in `find /data/ttt-apks/ -type f -name \*.apk` \
             /data/malware-apks/ikarus/*/*_[0-9]* \
             /data/malware-apks/github.com/*/*/*/*/*/*.apk; do
    outpath=${f#/data/malware-apks/}
    outpath=${outpath#/data/ttt-apks/}
    output=/data/ttt-apks/extracted-features/unzip-faup/${outpath}.unzip-faup.csv
    test -e "$output" && continue
    test -d "$(dirname $output)" || mkdir -p "$(dirname $output)"
    # use -c rather than -p to send the filenames to faup
    { unzip -c "$f" | grep --text -Eo '[^ \t<>#()]*\w\.\w\w[^ \t<>#()]*' |  ~/code/stricaud/faup/build/src/tools/faup -p | grep --text -v -e ',no_tld$' -e ',unknown_tld$' | sort -u > "$output"; } &
    i=$((i+1))
    if [ $i -gt 90 ]; then
	date
	wait
	i=0
    fi
done
