#!/bin/bash -x

export LC_ALL=C.UTF-8

. /data/malware-apks/code/jedisctl/ipgrep/venv/bin/activate

i=0
for f in /data/malware-apks/androzoo/top10ish-per-tracker-sdk/*.apk \
             /data/malware-apks/known-good/f-droid.org/*/*.apk \
             /data/malware-apks/ikarus/*/*_[0-9]* \
             /data/malware-apks/random-google-play/*.apk \
             /data/malware-apks/covid-19-set/*/*.apk \
             /data/malware-apks/github.com/*/*/*/*/*/*.apk; do
    outpath=${f#/data/malware-apks/}
    outpath=${outpath#/data/ttt-apks/}
    output=/data/ttt-apks/extracted-features/unzip-ipgrep/${outpath}.unzip-ipgrep
    test -e "$output" && continue
    test -d "$(dirname $output)" || mkdir -p "$(dirname $output)"
    # use -c rather than -p to send the filenames to ipgrep
    { unzip -c "$f" | buffer -m 20M | timeout 10m python3 /data/malware-apks/code/jedisctl/ipgrep/ipgrep.py --timeout 30 --tries 2 --servers 127.0.0.1 > "$output" 2>&1; } &
    i=$((i+1))
    if [ $i -gt 90 ]; then
        date
        wait
        i=0
    fi
done
